--
-- PostgreSQL database dump
--

-- Dumped from database version 12.20 (Ubuntu 12.20-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.20 (Ubuntu 12.20-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, username) FROM stdin;
7	$2a$10$//5lb6YBY82c0e8E7X3Luu6DnxBt8N7liNCad5Lsg6uVi9365Cb7e	onuryilmazo
8	$2a$10$aw8CjCZxCJVVaOFiNe9imedB3X9fyv99lSrf9FAsCNu8usPD4E/xm	onuryilmaz
9	$2a$10$kw6ftvxqW9MtBNtTU3NMyOV0vhLFQQ22e18YwW5OYwIHEuCWNVIf6	onuryilmazxo
10	$2a$10$LiqtPLStpX47.LzjfCb/geuHF2yaQs.g54S.GBj5T/4HyWCZ0gMHG	hadibakalim
11	$2a$10$apIC56J5loJ3ZzOEcy.tku2CCx/4ZKsrUpd4vswxnFLcKvl1PIMBG	callisnado
12	$2a$10$shGXcT9eGEqIYmVb7i8lWOqCRWYBgVzT4ZnIUoan/xhd4cZ1C7QLq	testo
13	$2a$10$LGS5ASL3UY/I2v2qYMm33etc37Wbo7RtfuZ9AE13AldXZkFmy7pNe	yansoapp
15	$2a$10$ErPutq5dlty9gH3KLSzf9ukfA.bWLI7uwdFzIrtj7sfQ6/oG8.PZ2	1234
16	$2a$10$WfJYewW7TkR4Q2AuZEdsT.oH1FKgE.Li9QjgXrZ3ocacYxch/XYJ.	12
17	$2a$10$oGT1Kss.hFfcDqyi2lrKM.0G5dqPiFyHbpF4CWc6inow5YlX.6V82	12345
18	$2a$10$.nSOzQafvCDvp188Q0r0HeQ4mnf/mKkwtCMqfh8xv2LDTR4qrNcLy	testuser
19	$2a$10$IGisbGd.ve7wBx0w8siEzuKWOctAHg3WWnXounfNQ7tUbWue4HgWi	12ad
20	$2a$10$uAT5OSrM5WtD9BxGqq877Ov.0jaYe7jdNDe.18lLAb.g86TRomVnG	testuser2
21	$2a$10$8vlvup43vVfxaKVEiYQfVO6xoExUROtxcASh7Yz6OHaqqksIBhPIe	deneme
23	$2a$10$N0gt7HFv0tGLKHMYcM8L.uW9dbR.vcHIfzyxF9lC/jdAxB2PzZb1S	testeruserss
24	$2a$10$m7cUXpftlE9YvHzhRTVnHuThkgHmhD4pW1.4UnAEi.WwGokkzVMiq	123c1c 12
25	$2a$10$9a2qKq0Aqil/z93Z66eAY.40jpnOpS52oQbeI14UUoUGl3PbHs/Hm	asd
26	$2a$10$k53bs9XIglk7uzlYKrXFR.E3KUxXZ3O5DJSP8gO57eUTWcgwRnQUS	asd3
27	$2a$10$gYBk08Ii9z2TiPyWJvphuOyzhG/d5QLcIcuO4yXlYxyCiWw7uzlv2	qweasd
28	$2a$10$cCyXx7vIJe7wVbIMC5TZZOYBnksiYMTJJlD2K.TL6Iyn4Klyop9Va	qwer
29	$2a$10$qCoFOh1QE1LgBM00qnSqX..b43T.2PIdXVvQgot0VQ7RfVVC86V4O	123456
31	$2a$10$26dJBIHVKFx9cxRPSxr6tuWkRgqMi.ElM1RAXP96z7QjBtHeoQm7K	123
32	$2a$10$LZ4r3axaXxPlVbukOg1VeOqUtGazKm2VtN8.561bdVy7KJiqgXCOS	1234567
33	$2a$10$Jk99W9tjjmBXCGE3WcdVmemudunHyUL09RcAHzI4akde3ukFnLhJu	123qw
34	$2a$10$Cp3J1sVCOQJygaeD.0I2FevWwU4zQ7xxzB7Fdsm1NqdINGUhJtiOu	123qweasd
35	$2a$10$9IB5bR.uY21arOiJXFe9zORIA5Pg2waMsskXBykp8VqAosHBKruRW	user123user
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 35, true);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

